# Generated by Django 4.0.4 on 2022-06-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='complit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='detail',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.productdetail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
                ('product', models.ManyToManyField(to='home.product')),
            ],
        ),
    ]
