# Generated by Django 4.0.4 on 2022-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart_complit_cart_detail_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
