# Generated by Django 4.0.4 on 2022-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
