# Generated by Django 4.0.4 on 2022-07-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_productdetail_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=16)),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Complted'), ('On the way', 'on the way')], default='Order Processing', max_length=22)),
                ('date', models.DateField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
            ],
        ),
    ]
